### ISSUE TITLE
Psix on samrt-seq2 data runs but saves nothing to directory "save_files_in" 

### ISSUE THREAD

**Issue by ZoeyZgee** [lareaulab/psix#6]
Hi,
Thank you for developing such a good tool！
I'm trying to get this running on our dataset which is a smart-seq2 STAR run(100 samples).

`import psix
psix_object = psix.Psix()
psix_object.junctions2psi(
        sj_dir='~/zzy/scRNA_AS/SJout/v1/',
        intron_file='psix_annotation.tab',
        tpm_file='~/zzy/gene_tpm',
        save_files_in='psix_output/'
        )

psix_object.run_psix(latent='~/zzy/gene_pca1_2', 
                     n_random_exons=200, 
                     n_neighbors=10,
                     n_jobs=10,
                     )`
When I first ran Psix, there was an error, so I modified the code.
![b2ed014913e061c2cb8ef336dbed239](https://user-images.githubusercontent.com/118446607/202445289-047f56c8-e22b-4b4c-a3f3-92853531068f.png)
![125cc4660d6c57c24c6a6bfd92b6064](https://user-images.githubusercontent.com/118446607/202445717-abaeb53e-ab98-4c55-8bfc-c974531462cd.png)
Then there was another error:
![945a9d5e4c09e11b260ba5ea18a5af8](https://user-images.githubusercontent.com/118446607/202445962-9f6d01ef-910c-4131-a869-c6961721c07d.png)
So that I modified the code again
![fe55122a6690946995964eb5c779537](https://user-images.githubusercontent.com/118446607/202446381-0be5c9ce-1e92-4fee-9a06-7d1b5db7eb6d.png)
After I modified these two codes, Psix can run out, but there was no psix.result in the output.
![8e020ba2ec9e2ec0d850f6c81994852](https://user-images.githubusercontent.com/118446607/202446920-b6eaa72f-c59b-48fe-ad07-d400805d1e2f.png)
![6056ce0426b7187d12a6c9743bb499b](https://user-images.githubusercontent.com/118446607/202447049-568cd83f-4408-47f3-ab76-29b92d6a5c78.png)

How could I solve this problem?
Thank you very much!

**Comment by ZoeyZgee** [comment]
The whole process of running Psix was very fast, which is a little abnormal, so i didn' t know if it was caused by my code changes. I would be grateful if you could give me some tips. Thank you!

**Comment by cfbuenabadn** [comment]
Hello! Thanks so much for reaching out. The code changes that you made fix a bug; thanks for catching that. I'll fix it and push asap, but what you did should work for you in the meantime.

As for Psix not saving anything after running, have you tried running the command `psix_object.save_psix_object('your/output/path/')` after `psix_object.run_psix()`?

**Comment by ZoeyZgee** [comment]
Thank you very much for your prompt reply! I've added a line of code now, but have a new error that I don't know how to fix.
![6f1064e10610e64561597b48e5ce1da](https://user-images.githubusercontent.com/118446607/202476664-fe250382-35da-4483-80f3-fd44afd0afd1.png)
![6b4c1f709bca4e5b9278a193b01eebe](https://user-images.githubusercontent.com/118446607/202476597-12591fe6-5a89-4176-8065-56604eacc3da.png)
![2f5030fee0996c41396d79b3ad91954](https://user-images.githubusercontent.com/118446607/202476625-36506900-f349-4923-b961-c437ae70ef92.png)

**Comment by ZoeyZgee** [comment]
And I ran Psix in a very short time to finish (less than two minutes in total), so I feel something is wrong. Is it caused by the fact that I have too few samples?
Thanks again for your prompt reply and help.

**Comment by cfbuenabadn** [comment]
I haven't seen that error before. I'll take a look and get back to you asap.

**Comment by ZoeyZgee** [comment]
Hello! I changed the parameter: "n_random_exons=1000" and was surprised to get psix.result! I would like to ask what is the purpose of setting the parameter "n_random_exons"? Is "2000" the default value or the recommended value? I found that setting it to "1000" and "2000" gives the same result.

**Comment by cfbuenabadn** [comment]
`n_random_exons` determines how many permutations Psix creates for calculating the empirical p-value of an exon. In principle, the higher this number is the better, but in practice very large numbers make Psix slow and only get diminishing returns. 1000 or 2000 should be enough for most datasets.

I am puzzled why setting it to 200 created the aforementioned error, but I'm glad you got it resolved. I'll check what's the breaking point and set a fixed minimum. Thank you for you help making Psix better!

**Comment by ZoeyZgee** [comment]
I have got it!
Thank you very much for your prompt reply and because of that my issue was fully resolved. Again, kudos to you great developers and awesome Psix!
